### PR TITLE
remove code in pictures, using lstlisting instead.

### PR DESCRIPTION
**Pull request by SebastianMygind**
Fix random textidote warning in calculations.tex

### CODE REVIEW

**Review by MadsHeilmann — CHANGES_REQUESTED** [review]
Forget this comment i posted earlier:

Remember to wrap the code in the {figure} thing, such that the compiler will place it where it seems fit, just like graphs and such.

Example:

\begin{figure}
\begin{lstlisting}
*other information*
\end{lstlisting}
\end{figure}

**Review by MadsHeilmann — APPROVED** [review]

**Review by Danar435 — APPROVED** [review]

**Comment by SebastianMygind** [comment]
@MadsHeilmann I see what you mean, but how do i get it to work with the label and caption tags? when i try:
\begin{figure}\label{fig:somethin}
\begin{lstlisting}

it wants a label tag in the listing aswell. The lstlisting seems to work fine as is, so i am unsure what is the best solution

**Comment by SebastianMygind** [comment]
@MadsHeilmann I also think it is better without the figure tag. This is because I want the code "inline" and with the figure tag the compiler places it where it wants, which in this case makes the text seem weird.

**Comment by MadsHeilmann** [comment]
> @MadsHeilmann I also think it is better without the figure tag. This is because I want the code "inline" and with the figure tag the compiler places it where it wants, which in this case makes the text seem weird.

That makes a lot of sense. I agree. That is also why i mentioned to forget my comment, as i regretted it :)

**Pull request merged**
